import "server-only";
import type { HotelGuide } from "./hotelGuides";
import type { HotelPhotoCredit } from "./hotelPhotoCredit";
type Candidate = { imageUrl: string; credit: HotelPhotoCredit };
// Research candidates are server-only and may only be selected by a gated demo route.
export const hotelDemoPhotos: Record<string, Candidate> = {
"hilton-gaslamp": {"imageUrl": "https://www.hilton.com/im/en/SANGQHF/9421930/sangqhf-new-exterior-1.jpg?ch=3333&cw=5000&gravity=NorthWest&impolicy=crop&rh=1600&rw=2400&xposition=0&yposition=1", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://www.hilton.com/en/hotels/sangqhf-hilton-san-diego-gaslamp-quarter/gallery/", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"ac-hotel-gaslamp": {"imageUrl": "https://cache.marriott.com/is/image/marriotts7prod/ar-sanar-exterior-dusk94546-95883%3AWide-Hor?fit=constrain&wid=2400", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://www.marriott.com/en-us/hotels/sanar-ac-hotel-san-diego-downtown-gaslamp-quarter/photos/", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"moxy-gaslamp": {"imageUrl": "https://cache.marriott.com/content/dam/marriott-renditions/SANOX/sanox-exterior-6034-hor-wide.jpg", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://www.marriott.com/en-us/hotels/sanox-moxy-san-diego-downtown-gaslamp-quarter/photos/", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"marriott-gaslamp": {"imageUrl": "https://cache.marriott.com/content/dam/marriott-renditions/SANGL/sangl-exterior-7410-hor-wide.jpg", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://www.marriott.com/en-us/hotels/sangl-san-diego-marriott-gaslamp-quarter/photos/", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"residence-inn-gaslamp": {"imageUrl": "https://cache.marriott.com/content/dam/marriott-renditions/SANRG/sanrg-exterior-0062-hor-wide.jpg", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://www.marriott.com/en-us/hotels/sanrg-residence-inn-san-diego-downtown-gaslamp-quarter/photos/", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"orli-la-jolla": {"imageUrl": "https://orlidev.wpengine.com/wp-content/uploads/2022/09/Orli-Exterior-231-web.jpg", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://stayorli.com/gallery", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"hotel-la-jolla": {"imageUrl": "https://www.hilton.com/im/en/SANCUQQ/13832044/sancu-exterior-ii.jpg?ch=3024&cw=4536&gravity=NorthWest&impolicy=crop&rh=1600&rw=2400&xposition=1&yposition=0", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://www.hilton.com/en/hotels/sancuqq-hotel-la-jolla/gallery/", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"la-jolla-beach-tennis-club": {"imageUrl": "https://media.truetour.app/assets/media/b1af02f7-8a1b-4a92-b195-3529321e6d32.jpg", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://visitingmedia.com/app/properties/2234/all-assets-share?shareId=6293", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"cormorant-la-jolla": {"imageUrl": "https://www.cormorantlajolla.com/wp-content/uploads/Cormorant-Website-Mockup.pdf-image-005.png", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://www.cormorantlajolla.com/", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"omni-san-diego": {"imageUrl": "https://www.omnihotels.com/-/media/images/hotels/sandtn/photogallery/hotel/sandtn-omni_san_diego_hotel-2023_exterior_daytime_1170x660.jpg?hash=46BD5E81A529149FA631FB99ADC549A98B192985&mw=1536", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://www.omnihotels.com/en/hotels/san-diego", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
"margaritaville-gaslamp": {"imageUrl": "https://d1l4e1efm2qo9x.cloudfront.net/margaritavilleresorts.com-1367967347/cms/cache/v2/65ea47c38813b.jpg/768x550/fit%3Bc%3A0%2C0%2C1920%2C1920%3Bfp%3A44%2C18/80/b84c08c79d4cae170c0d559aa4840398.jpg", "credit": {"attribution": "Photo source: hotel gallery. Photographer not supplied.", "sourceUrl": "https://www.margaritavilleresorts.com/margaritaville-hotel-san-diego/gallery", "status": "permission-pending", "note": "Internal example only. Permission has not been recorded; do not publish or redistribute."}},
};
export const licensedHotelPhotos: Record<string, Candidate> = {
"us-grant": {"imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/The_US_Grant_Hotel_Facade.jpg/1280px-The_US_Grant_Hotel_Facade.jpg", "credit": {"attribution": "Abhishek Padmanabhuni", "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_US_Grant_Hotel_Facade.jpg", "status": "licensed", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "note": "Original photograph; display cropped to fit. Historic photo, not a statement of current condition."}},
"westin-gaslamp": {"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Westin_Gaslamp_Quarter_1.JPG", "credit": {"attribution": "\u00a9 BrokenSphere / Wikimedia Commons", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Westin_Gaslamp_Quarter_1.JPG", "status": "licensed", "license": "CC BY-SA 3.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/", "note": "Original photograph; display cropped to fit. Historic photo, not a statement of current condition."}},
"omni-san-diego": {"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/76/San_Diego%2C_Oct._2016_12.jpg", "credit": {"attribution": "Another Believer", "sourceUrl": "https://commons.wikimedia.org/wiki/File:San_Diego,_Oct._2016_12.jpg", "status": "licensed", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "note": "Original photograph; display cropped to fit. Historic photo, not a statement of current condition."}},
};
export function applyHotelPhoto(hotel: HotelGuide, demo = false): HotelGuide & { heroCredit?: HotelPhotoCredit } {
  const candidate = (demo ? hotelDemoPhotos[hotel.slug] : undefined) || licensedHotelPhotos[hotel.slug];
  const pending = Object.values(hotelDemoPhotos).some(photo => photo.imageUrl === hotel.heroImageUrl);
  if (pending && !demo) hotel = { ...hotel, heroImageUrl: undefined };
  if (!candidate) return hotel;
  // Existing saved media always wins. Never attach someone else's credit to it.
  if (hotel.heroImageUrl && hotel.heroImageUrl !== candidate.imageUrl) return hotel;
  return { ...hotel, heroImageUrl: candidate.imageUrl, heroAlt: hotel.heroAlt || `${hotel.name} property photograph`, heroCredit: candidate.credit };
}
