-- SingHUB homepage poll vote persistence
-- Run in Supabase SQL editor before enabling live voting.

create table if not exists public.poll_votes (
  id bigint generated by default as identity primary key,
  poll_slug text not null,
  option_id text not null,
  voter_hash text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists poll_votes_one_vote_per_poll
  on public.poll_votes (poll_slug, voter_hash);

create index if not exists poll_votes_results_lookup
  on public.poll_votes (poll_slug, option_id);

alter table public.poll_votes enable row level security;

-- No public policies are intentionally created. The website API writes and reads
-- through the server-side Supabase service role so voter hashes are never exposed.

comment on table public.poll_votes is
  'Anonymous SingHUB homepage poll votes. voter_hash is a one-way server-side hash used only to prevent duplicate browser votes.';
