-- SingHUB homepage poll vote persistence
-- Run this whole file once in the Supabase SQL editor.

create table if not exists public.poll_votes (
  id bigint generated by default as identity primary key,
  poll_slug text not null,
  option_id text not null,
  voter_hash text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists poll_votes_one_vote_per_poll
  on public.poll_votes (poll_slug, voter_hash);

create index if not exists poll_votes_results_lookup
  on public.poll_votes (poll_slug, option_id);

alter table public.poll_votes enable row level security;

-- Keep the raw table private. The website may only call the narrow security-definer
-- functions below, so anonymous users can submit a vote and read aggregate totals
-- without ever being able to query voter hashes or individual vote rows.

create or replace function public.poll_results(p_poll_slug text)
returns table(option_id text, votes bigint)
language sql
security definer
set search_path = public
as $$
  select pv.option_id, count(*)::bigint as votes
  from public.poll_votes pv
  where pv.poll_slug = p_poll_slug
  group by pv.option_id;
$$;

create or replace function public.submit_poll_vote(
  p_poll_slug text,
  p_option_id text,
  p_voter_hash text
)
returns table(selected_option_id text, inserted boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_option text;
  existing_option text;
begin
  insert into public.poll_votes (poll_slug, option_id, voter_hash)
  values (p_poll_slug, p_option_id, p_voter_hash)
  on conflict (poll_slug, voter_hash) do nothing
  returning poll_votes.option_id into inserted_option;

  if inserted_option is not null then
    return query select inserted_option, true;
    return;
  end if;

  select pv.option_id
    into existing_option
  from public.poll_votes pv
  where pv.poll_slug = p_poll_slug
    and pv.voter_hash = p_voter_hash
  limit 1;

  return query select existing_option, false;
end;
$$;

revoke all on function public.poll_results(text) from public;
revoke all on function public.submit_poll_vote(text, text, text) from public;
grant execute on function public.poll_results(text) to anon, authenticated;
grant execute on function public.submit_poll_vote(text, text, text) to anon, authenticated;

comment on table public.poll_votes is
  'Anonymous SingHUB homepage poll votes. voter_hash is a one-way server-side hash used only to prevent duplicate browser votes.';
