"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {VenueListing} from '@/types';
import {accountClient,sendAccountLink} from '@/lib/v2/singerAccount';
import type {useSingerAccount} from './useSingerAccount';
export function AccountServiceDialog({state,venues,request,onClose,onMessage}:{state:ReturnType<typeof useSingerAccount>;venues:VenueListing[];request:'alias'|'signin'|'performance'|null;onClose:()=>void;onMessage:(message:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [pending,setPending]=useState(false);const handled=useRef('');const [message,setMessage]=useState('');const [sent,setSent]=useState(false);const [newStar,setNewStar]=useState<{song:string;venueName:string;venueSlug:string}|null>(null);
 useEffect(()=>{if(!request)return;queueMicrotask(()=>{setNewStar(null);setSent(false);setMessage(new URLSearchParams(location.search).has('authError')?'Your sign-in link expired or could not be completed. Request a new link and open it in the browser where you started.':'');});},[request]);
 useEffect(()=>{if(request)dialog.current?.showModal();else dialog.current?.close();},[request]);
 useEffect(()=>{const params=new URLSearchParams(location.search);const slug=params.get('save');if(!slug||!state.user||!state.account||handled.current===slug)return;const venue=venues.find(venue=>venue.slug===slug);if(!venue)return;handled.current=slug;
  void accountClient().from('singer_saved_venues').upsert({user_id:state.user.id,venue_slug:venue.slug,venue_name:venue.venueName,neighborhood:venue.neighborhood}).then(async({error})=>{if(error){handled.current='';onMessage(error.message);return;}history.replaceState({},'',location.pathname);onMessage(venue.venueName+' saved.');onClose();await state.refresh();});
 },[state,venues,onMessage,onClose]);
 const signedIn=Boolean(state.user);
 const starCaption=newStar?'I earned a new performance star on SingHUB! ★\n'+newStar.song+' at '+newStar.venueName+' 🎤\n\nFind your next karaoke night on SingHUB.':'';
 async function copyStar(){if(!newStar)return;try{await navigator.clipboard.writeText(starCaption+'\n\n'+location.origin+'/venues/'+newStar.venueSlug);setMessage('Caption and venue link copied.');}catch{setMessage('Select the caption below to copy it.');}}
 async function shareStar(){if(!newStar)return;try{if(navigator.share)await navigator.share({title:'My new SingHUB performance star',text:starCaption,url:location.origin+'/venues/'+newStar.venueSlug});else await copyStar();}catch(error){if(!(error instanceof Error&&error.name==='AbortError'))setMessage('Sharing could not open. You can copy the caption instead.');}}

 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setPending(true);setMessage('');try{
  if(!state.user){await sendAccountLink(String(form.get('email')||''),location.pathname+location.search);setSent(true);setMessage('Check your email for your sign-in link. Open it in this browser to finish. Check spam if it does not arrive.');return;}
  const client=accountClient();if(request==='alias'){const {error}=await client.from('singer_profiles').upsert({user_id:state.user.id,karaoke_alias:String(form.get('alias')||'').trim()||null,updated_at:new Date().toISOString()});if(error)throw error;onMessage('Karaoke alias saved.');}
  if(request==='performance'){
   const slug=new URLSearchParams(location.search).get('perform');const venue=venues.find(venue=>venue.slug===slug);if(!venue)throw new Error('Choose SingHERE from a venue to record this performance.');
   const {error}=await client.from('singer_performances').insert({user_id:state.user.id,song_title:String(form.get('song')||'').trim(),artist:String(form.get('artist')||'').trim()||null,venue_slug:venue.slug,venue_name:venue.venueName,performed_on:String(form.get('date')||'')});if(error)throw error;history.replaceState({},'',location.pathname);setNewStar({song:String(form.get('song')||'').trim(),venueName:venue.venueName,venueSlug:venue.slug});onMessage('Performance recorded. Your star is earned.');await state.refresh();return;
  }
  await state.refresh();onClose();
 }catch(error){const message=error instanceof Error?error.message:'Your account could not be updated.';setMessage(message);onMessage(message);}finally{setPending(false);}}
 return <dialog className="account-service-dialog" ref={dialog} aria-labelledby="account-action-title" onCancel={onClose}><div className="modal-shell"><header className="modal-head"><strong id="account-action-title">{newStar?'You earned a performance star!':signedIn?(request==='performance'?'Record your performance':'Karaoke alias'):'Sign in to My SingHUB'}</strong><button className="icon-button" aria-label="Close account action" onClick={onClose}>×</button></header>{newStar?<div className="panel account-service-form"><p>Share your new star?</p><p>Your performance is saved and your star is already on your jacket. Sharing is optional.</p><div className="caption" style={{whiteSpace:'pre-wrap'}}>{starCaption}</div><button className="button primary" type="button" onClick={()=>void shareStar()}>Share my new star</button><button className="button" type="button" onClick={()=>void copyStar()}>Copy caption</button><button className="text-button" type="button" onClick={onClose}>Not now</button><p className="free-rule" role="status">{message||'Choose an app, then review your post before sharing.'}</p></div>:<form className="panel account-service-form" onSubmit={submit}>
 {!signedIn?<label>Email address<input className="account-service-input" name="email" type="email" autoComplete="email" required /></label>:request==='performance'?<><label>Song title<input className="account-service-input" name="song" maxLength={180} required /></label><label>Artist<input className="account-service-input" name="artist" maxLength={180} /></label><label>Performed on<input className="account-service-input" name="date" type="date" required /></label></>:<label>Karaoke alias<input className="account-service-input" name="alias" defaultValue={state.account?.alias||''} maxLength={40} /></label>}
 <button className="button primary" disabled={pending||(!signedIn&&sent)}>{pending?'Working…':signedIn?'Save':sent?'Link sent · Check your email':'Email my sign-in link'}</button>{!signedIn&&sent&&<button className="text-button" type="button" onClick={()=>{setSent(false);setMessage('Update your email address below, then request a new link.');}}>Use a different email</button>}<p className="free-rule" role="status">{message||(signedIn?'Saved privately to your SingHUB account.':'Confirm the email link before anything is saved.')}</p>
 </form>}</div></dialog>;
}
