'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {accountClient,sendAccountLink} from '@/lib/v2/singerAccount';
import {trackEvent} from '@/lib/analytics';
import './gigStubs.css';
export function GigStubCheckIn({venueSlug,venueName}:{venueSlug:string;venueName:string}){
 const dialog=useRef<HTMLDialogElement>(null);const [pending,setPending]=useState(false);const [needsSignIn,setNeedsSignIn]=useState(false);const [sent,setSent]=useState(false);const [saved,setSaved]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{if(new URLSearchParams(location.search).get('checkin')==='1')dialog.current?.showModal();},[]);
 async function checkIn(method:'self_reported'|'location_matched'){
  setPending(true);setMessage('');try{
   const {data,error}=await accountClient().auth.getSession();if(error)throw error;if(!data.session){setNeedsSignIn(true);return;}
   const locationData=method==='location_matched'?await new Promise<GeolocationCoordinates>((resolve,reject)=>{if(!navigator.geolocation){reject(new Error('Location is unavailable. You can record a self-reported visit.'));return;}navigator.geolocation.getCurrentPosition(p=>resolve(p.coords),()=>reject(new Error('Location was unavailable. You can record a self-reported visit.')),{enableHighAccuracy:true,timeout:10000,maximumAge:30000});}):undefined;
   const response=await fetch('/api/gig-stubs',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+data.session.access_token},body:JSON.stringify({venueSlug,method,...(locationData?{location:{latitude:locationData.latitude,longitude:locationData.longitude,accuracy:locationData.accuracy}}:{})})});
   const result=await response.json();if(response.status===401){setNeedsSignIn(true);return;}if(!response.ok)throw new Error(result.error);
   setSaved(true);setMessage(result.alreadyCheckedIn?'You already checked in here this karaoke night.':result.collected?'New room. New Gig Stub. It’s in My SingHUB.':'Welcome back. Your visit is saved; you already have this room’s Gig Stub.');
   trackEvent('venue_check_in',{venue_slug:venueSlug,check_in_method:method,new_gig_stub:Boolean(result.collected),duplicate:Boolean(result.alreadyCheckedIn)});
  }catch(error){setMessage(error instanceof Error?error.message:'Your visit was not saved.');}finally{setPending(false);}
 }
 async function signIn(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);try{await sendAccountLink(String(new FormData(event.currentTarget).get('email')),location.pathname+'?checkin=1');setSent(true);setMessage('Check your email. Open the link in this browser, then confirm your visit.');}catch(error){setMessage(error instanceof Error?error.message:'Sign-in link was not sent.');}finally{setPending(false);}}
 return <div className="gig-check-in"><button type="button" className="gig-check-in-button" onClick={()=>{setMessage('');setSaved(false);setNeedsSignIn(false);setSent(false);dialog.current?.showModal();trackEvent('venue_check_in_open',{venue_slug:venueSlug});}}>I’m here · Collect a Gig Stub</button><dialog className="gig-dialog" ref={dialog} aria-labelledby={'gig-title-'+venueSlug} onClick={e=>{if(e.target===e.currentTarget)e.currentTarget.close();}}><button className="gig-close" aria-label="Close check-in" onClick={()=>dialog.current?.close()}>×</button><p className="gig-eyebrow">Keep the stub. Remember the room.</p><h2 id={'gig-title-'+venueSlug}>{venueName}</h2><p>Here tonight? Collect one Gig Stub for this venue. Every return visit adds to your history.</p><p className="gig-fine">This records a visit, not a performance. Location is optional; self-reported visits are labeled. Your collection is private. We don’t save your precise location.</p>{needsSignIn?<form onSubmit={signIn}><label>Email<input name="email" type="email" autoComplete="email" required /></label><button type="submit" disabled={pending||sent}>{sent?'Link sent':'Email me a sign-in link'}</button></form>:!saved&&<div className="gig-actions"><button disabled={pending} onClick={()=>void checkIn('location_matched')}>{pending?'Working…':'Check my location & check in'}</button><button disabled={pending} onClick={()=>void checkIn('self_reported')}>Record a self-reported visit</button></div>}<p role="status">{message}</p>{saved&&<Link href="/account#gig-stubs">See my Gig Stubs →</Link>}</dialog></div>;
}
