/* Literal port of authoritative Site v37. Preserve markup and CSS relationships. */
/* eslint-disable @next/next/no-img-element */
"use client";
import { HotelHero } from "./HotelHero";
import Link from "next/link";
import { useCallback,useEffect,useRef,useState,type FormEvent } from 'react';
import { useV2Actions,useViewerInitials } from './actions';
import { useListReturn } from './listReturn';
import { HotelVenueCard } from './VenueRows';
import { selectHotelStandouts,type HotelRowData } from '@/lib/v2/presentation';

import {accountClient,saveHotelPlan,sendAccountLink} from '@/lib/v2/singerAccount';
import "./styles/hotel.css";
export function HotelGuideTemplate({hotelName,hotelShortName,hotelSlug,hotelArea,heroImageUrl,heroAlt,heroPosition,tonightVenues,weekVenues,weeklyCount,tonightCount}:{hotelName:string;hotelShortName:string;hotelSlug:string;hotelArea:string;heroImageUrl?:string;heroAlt?:string;heroPosition?:string;tonightVenues:HotelRowData[];weekVenues:HotelRowData[];weeklyCount:number;tonightCount:number}) {
const root=useRef<HTMLDivElement>(null);const viewerInitials=useViewerInitials();const [mode,setMode]=useState<'tonight'|'week'>('tonight');const [planVenue,setPlanVenue]=useState<HotelRowData|null>(null);
useListReturn({mode},saved=>{if(saved?.mode==='tonight'||saved?.mode==='week')setMode(saved.mode);});
const active=mode==='tonight'?tonightVenues:weekVenues;const groups={walkable:active.filter(item=>item.tier==='walkable'),quick:active.filter(item=>item.tier==='quick'),standout:selectHotelStandouts(active)};
const actions=useV2Actions(root,{venues:active.map(row=>row.venue)});const {toast}=actions;
const [savedPlans,setSavedPlans]=useState<string[]>([]);const [email,setEmail]=useState('');const [saving,setSaving]=useState(false);
const markSaved=useCallback((slug:string)=>setSavedPlans(current=>current.includes(slug)?current:[...current,slug]),[]);
const openPlan=(item:HotelRowData)=>{setPlanVenue(item);requestAnimationFrame(()=>root.current?.querySelector<HTMLInputElement>('#plan-email')?.focus());};
useEffect(()=>{let active=true;try{const client=accountClient();void client.auth.getUser().then(async({data,error})=>{if(error||!data.user||!active)return;setEmail(data.user.email||'');const result=await client.from('hotel_guest_plans').select('venue_slug').eq('user_id',data.user.id).eq('hotel_slug',hotelSlug);if(result.error){toast(result.error.message);return;}if(active)setSavedPlans((result.data||[]).map(row=>row.venue_slug));const params=new URLSearchParams(location.search);const slug=params.get('plan');const venue=[...tonightVenues,...weekVenues].find(venue=>venue.slug===slug);if(venue){try{await saveHotelPlan({slug:hotelSlug,name:hotelName},venue,params.get('saveHotel')!=='0');if(active){markSaved(venue.slug);toast('Added to your plan.');history.replaceState({},'',location.pathname);}}catch(error){toast(error instanceof Error?error.message:'Your plan could not be saved.');}}}).catch(()=>{});}catch{}return()=>{active=false;};},[hotelSlug,hotelName,tonightVenues,weekVenues,markSaved,toast]);
async function submitPlan(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!planVenue)return;const form=new FormData(event.currentTarget);const saveHotel=form.get('saveHotel')==='on';setSaving(true);try{const saved=await saveHotelPlan({slug:hotelSlug,name:hotelName},planVenue,saveHotel);if(saved){markSaved(planVenue.slug);setPlanVenue(null);toast(saveHotel?'Added to your plan. '+hotelShortName+' was saved with this trip.':'Added to your plan.');}else{const next='/hotel/'+hotelSlug+'?plan='+encodeURIComponent(planVenue.slug)+'&saveHotel='+(saveHotel?'1':'0');await sendAccountLink(email,next);setPlanVenue(null);toast('Check your email to confirm sign-in and save your plan.');}}catch(error){toast(error instanceof Error?error.message:'Your plan was not saved.');}finally{setSaving(false);}}

useEffect(()=>{const listener=(event:KeyboardEvent)=>{if(event.key==='Escape')setPlanVenue(null);};document.addEventListener('keydown',listener);return ()=>document.removeEventListener('keydown',listener);},[]);

return <div className={"v2-hotel"+(mode === "week" ? " week-mode" : "")} ref={root}>

<header className="appbar"><Link href="/"><img className="logo" src="/images/singhub-v2/singhub-wordmark.png" alt="SingHUB" /></Link><nav className="primary-nav" aria-label="Primary"><Link href="/">{"Discover"}</Link><a className="active" href={"/hotel/"+hotelSlug}>{"Hotel guide"}</a><a href="/find-karaoke">{"Venues"}</a><Link href="/hosts">{"Hosts"}</Link><Link href="/hotel">{"Hotels"}</Link><a href="/singboard">{"SingBOARD"}</a></nav><a className="account" href="/account"><span>{"My SingHUB"}</span><i className="avatar">{viewerInitials}</i></a></header>
<main>
<HotelHero hotelName={hotelName} hotelShortName={hotelShortName} hotelArea={hotelArea} heroImageUrl={heroImageUrl} heroAlt={heroAlt} heroPosition={heroPosition} />
<div className="experience-shell">
<section className="concierge" aria-labelledby="welcome-title"><div className="concierge-inner"><div><p className="eyebrow">{'CURATED FOR GUESTS OF '+hotelShortName.toUpperCase()}</p><h2 id="welcome-title">{"New in town? Looking for a mic? Let me show you where San Diego really sings."}</h2></div><div className="concierge-copy"><p>{'San Diego has '+weeklyCount+' confirmed karaoke nights this week. Tonight, SingHUB has '+tonightCount+' live-karaoke listings to choose from.'}</p><p>{"Take a look at a few nearby options and plan your own local gig tour."}</p></div></div></section>
<section className="guide" aria-labelledby="guide-title">
<header className="guide-head"><div><p className="eyebrow">{"KARAOKE NEAR YOU"}</p><h2 id="guide-title">{"Find your room."}</h2></div><div className="guide-controls"><div className="plan-status" aria-live="polite">{"My plan "}<strong id="plan-count">{savedPlans.length}</strong></div><div className="mode-switch" role="group" aria-label="Schedule range"><button data-mode="tonight" aria-pressed={mode === 'tonight'} className={mode === 'tonight' ? 'active' : ''} onClick={()=>setMode('tonight')}>{"Tonight"}</button><button data-mode="week" aria-pressed={mode === 'week'} className={mode === 'week' ? 'active' : ''} onClick={()=>setMode('week')}>{"This week"}</button></div><button className="map-button" data-toast="Map view opened">{"Map view"}</button></div></header>
<div className="guide-notes" aria-label="Using the hotel guide"><div className="guide-note"><strong>{"Start with the night."}</strong><p>{"Use Tonight for what’s happening now. Switch to This Week if you’re planning around the rest of your stay."}</p></div><details className="guide-note"><summary>{"What is SingHUB?"}</summary><p>{"SingHUB is San Diego’s karaoke discovery guide. We bring venue schedules, room details, and recent verification dates into one place so you can spend less time searching and more time singing."}</p></details></div>
<section className="category" data-category={"walkable"}><header className="category-head"><span className="category-icon" aria-hidden="true"><span className="material-symbols-rounded">{"directions_walk"}</span></span><div><h3>{"Walkable"}</h3><p>{"If you want something you can reach in about 5–10 minutes, start here. Step outside, pick a room, and go."}</p></div><div className="slider-buttons"><button data-slide="prev" aria-label="Previous walkable venues" onClick={event=>{const slider=event.currentTarget.closest('.category')?.querySelector('.venue-slider');if(slider)slider.scrollBy({left:-1*Math.min(slider.clientWidth*.8,360),behavior:'smooth'});}}>{"‹"}</button><button data-slide="next" aria-label="Next walkable venues" onClick={event=>{const slider=event.currentTarget.closest('.category')?.querySelector('.venue-slider');if(slider)slider.scrollBy({left:1*Math.min(slider.clientWidth*.8,360),behavior:'smooth'});}}>{"›"}</button></div></header><div className="venue-slider">{groups.walkable.map(item=><HotelVenueCard key={item.slug} item={item} hotelName={hotelShortName} onPlan={()=>openPlan(item)} added={savedPlans.includes(item.slug)} />)}</div></section>
<section className="category" data-category={"quick"}><header className="category-head"><span className="category-icon" aria-hidden="true"><span className="material-symbols-rounded">{"directions_car"}</span></span><div><h3>{"Quick Ride"}</h3><p>{"If you don’t mind a short drive or rideshare, you have a few more neighborhood options."}</p></div><div className="slider-buttons"><button data-slide="prev" aria-label="Previous quick ride venues" onClick={event=>{const slider=event.currentTarget.closest('.category')?.querySelector('.venue-slider');if(slider)slider.scrollBy({left:-1*Math.min(slider.clientWidth*.8,360),behavior:'smooth'});}}>{"‹"}</button><button data-slide="next" aria-label="Next quick ride venues" onClick={event=>{const slider=event.currentTarget.closest('.category')?.querySelector('.venue-slider');if(slider)slider.scrollBy({left:1*Math.min(slider.clientWidth*.8,360),behavior:'smooth'});}}>{"›"}</button></div></header><div className="venue-slider">{groups.quick.map(item=><HotelVenueCard key={item.slug} item={item} hotelName={hotelShortName} onPlan={()=>openPlan(item)} added={savedPlans.includes(item.slug)} />)}</div></section>
<section className="category" data-category={"standout"}><header className="category-head"><span className="category-icon" aria-hidden="true"><span className="material-symbols-rounded">{"star"}</span></span><div><h3>{"Local Standouts"}</h3><p>{"If distance is no problem, these are the San Diego karaoke experiences worth talking about when you get home."}</p></div><div className="slider-buttons"><button data-slide="prev" aria-label="Previous local standouts" onClick={event=>{const slider=event.currentTarget.closest('.category')?.querySelector('.venue-slider');if(slider)slider.scrollBy({left:-1*Math.min(slider.clientWidth*.8,360),behavior:'smooth'});}}>{"‹"}</button><button data-slide="next" aria-label="Next local standouts" onClick={event=>{const slider=event.currentTarget.closest('.category')?.querySelector('.venue-slider');if(slider)slider.scrollBy({left:1*Math.min(slider.clientWidth*.8,360),behavior:'smooth'});}}>{"›"}</button></div></header><div className="venue-slider">{groups.standout.map(item=><HotelVenueCard key={item.slug} item={item} hotelName={hotelShortName} onPlan={()=>openPlan(item)} added={savedPlans.includes(item.slug)} />)}</div></section>
<div className="guide-exit"><span className="key-mark">{"SH"}</span><div><strong>{"The venue pin means verified karaoke on SingHUB."}</strong><p>{"Keep exploring with your hotel visit carried into the main SingHUB experience."}</p></div><a className="view-all" href={'/?source=hotel-'+hotelSlug}>{"View all karaoke"}</a></div>
<section className="install-strip" aria-label="Install SingHUB"><div><p className="eyebrow">{"TAKE IT WITH YOU"}</p><strong>{"Keep SingHUB one tap away."}</strong></div><button data-toast="SingHUB install prompt opened">{"Install SingHUB"}</button></section>
<footer><span>{"SingHUB local karaoke guide"}</span><span>{"Schedules from SingHUB’s canonical listings."}</span></footer>
</section>
</div>
</main>
<nav className="mobile-nav" aria-label="Mobile navigation"><Link href="/"><b>{"⌕"}</b>{"Discover"}</Link><a className="active" href={"/hotel/"+hotelSlug}><b>{"@"}</b>{"Hotel"}</a><a href="/find-karaoke"><b>{"●"}</b>{"Venues"}</a><Link href="/hosts"><b>{"♪"}</b>{"Hosts"}</Link><a href="/account"><b>{"◎"}</b>{"My SingHUB"}</a></nav>
<div className="plan-modal" id="plan-modal" hidden={!planVenue} onClick={event=>{if(event.target===event.currentTarget)setPlanVenue(null);}}><section className="plan-dialog" role="dialog" aria-modal="true" aria-labelledby="plan-title"><button className="plan-close" type="button" aria-label="Close" onClick={()=>setPlanVenue(null)}>{"×"}</button><p className="eyebrow">{"YOUR LOCAL GIG TOUR"}</p><h2 id="plan-title">{"Add "}<span id="plan-venue">{planVenue?.name || 'this venue'}</span>{" to your plan."}</h2><p>{"Enter your email and we’ll keep your karaoke picks together for this trip."}</p><form className="plan-form" onSubmit={submitPlan}><label htmlFor="plan-email">{"Email address"}</label><input id="plan-email" type="email" value={email} onChange={event=>setEmail(event.target.value)} autoComplete="email" placeholder="you@example.com" required /><label className="plan-check"><input id="save-hotel" name="saveHotel" type="checkbox" defaultChecked /><span>{'Save '+hotelShortName+' with this trip so your hotel guide is waiting in My SingHUB.'}</span></label><button className="plan-submit" type="submit" disabled={saving}>{saving?'Saving…':'Save my plan'}</button><p className="plan-privacy">{"We’ll email a sign-in link so you can save your plan to My SingHUB. No marketing opt-in is implied."}</p></form></section></div>
<div className="toast" role="status" aria-live="polite"></div>


{actions.overlay}
</div>;
}
