"use client";

import { useMemo, useState } from "react";
import type { LockedRoundupPayload, RoundupDraft, RoundupRenderFormat, RoundupState, RoundupVenueRow } from "@/lib/roundups/types";
import { lockRoundupAction, markRoundupReviewedAction, saveEditedRoundupDraftAction } from "@/app/admin/roundups/actions";

type RenderedSlide = { name: string; dataUrl: string };

function dims(format: RoundupRenderFormat) {
  return format === "story" ? { width: 1080, height: 1920 } : { width: 1080, height: 1350 };
}
function escapeText(value: string) { return value.replace(/\s+/g, " ").trim(); }
function wrap(ctx: CanvasRenderingContext2D, text: string, maxWidth: number) {
  const words = text.split(" "); const lines: string[] = []; let line = "";
  for (const word of words) { const next = line ? `${line} ${word}` : word; if (ctx.measureText(next).width > maxWidth && line) { lines.push(line); line = word; } else line = next; }
  if (line) lines.push(line); return lines;
}
function background(ctx: CanvasRenderingContext2D, width: number, height: number) {
  const gradient = ctx.createLinearGradient(0, 0, width, height); gradient.addColorStop(0, "#12071d"); gradient.addColorStop(.52, "#08111f"); gradient.addColorStop(1, "#23113a"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, width, height);
  ctx.globalAlpha = .16; for (let i=0;i<18;i++){ctx.beginPath();ctx.arc((i*173)%width,(i*257)%height,90+(i%4)*50,0,Math.PI*2);ctx.fillStyle=i%2?"#ff3ca6":"#49d9ff";ctx.fill();} ctx.globalAlpha=1;
}
function brand(ctx: CanvasRenderingContext2D, width: number) { ctx.textAlign="left"; ctx.fillStyle="#ffffff"; ctx.font="900 54px Arial"; ctx.fillText("SingHUB",72,92); ctx.fillStyle="#ff4daf"; ctx.fillRect(72,112,width-144,6); }
function footer(ctx: CanvasRenderingContext2D, width: number, height: number) { ctx.textAlign="center"; ctx.fillStyle="#b8c2d9"; ctx.font="700 28px Arial"; ctx.fillText("San Diego Karaoke • SingHUB.app",width/2,height-58); }
function canvasSlide(format: RoundupRenderFormat, draw:(ctx:CanvasRenderingContext2D,w:number,h:number)=>void) { const {width,height}=dims(format); const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas unavailable.");background(ctx,width,height);draw(ctx,width,height);return canvas.toDataURL("image/png"); }
function renderIntro(payload: LockedRoundupPayload, format: RoundupRenderFormat) { return canvasSlide(format,(ctx,w,h)=>{brand(ctx,w);ctx.textAlign="center";ctx.fillStyle="#49d9ff";ctx.font="900 52px Arial";ctx.fillText(payload.weekday.toUpperCase(),w/2,h*.32);ctx.fillStyle="#fff";ctx.font=`900 ${format==="story"?96:82}px Arial`;ctx.fillText("KARAOKE",w/2,h*.41);ctx.fillStyle="#ff4daf";ctx.fillText("ROUNDUP",w/2,h*.49);ctx.fillStyle="#d9e1ef";ctx.font="700 36px Arial";ctx.fillText(new Date(`${payload.date}T12:00:00`).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}),w/2,h*.57);ctx.fillStyle="#fff";ctx.font="800 30px Arial";ctx.fillText(`${payload.rows.length} places to sing`,w/2,h*.64);footer(ctx,w,h);}); }
function renderGroup(payload: LockedRoundupPayload, eventIds: string[], format: RoundupRenderFormat) { const rows=eventIds.map(id=>payload.rows.find(r=>r.eventId===id)).filter(Boolean) as RoundupVenueRow[]; return canvasSlide(format,(ctx,w,h)=>{brand(ctx,w);ctx.fillStyle="#fff";ctx.font="900 48px Arial";ctx.fillText(`${payload.weekday} Karaoke`,72,190);let y=270;const rowHeight=format==="story"?245:190;for(const row of rows){ctx.fillStyle="rgba(255,255,255,.07)";ctx.beginPath();ctx.roundRect(64,y-44,w-128,rowHeight-24,26);ctx.fill();ctx.fillStyle="#49d9ff";ctx.font="900 34px Arial";ctx.fillText(escapeText(row.venueName),92,y);ctx.fillStyle="#fff";ctx.font="700 27px Arial";ctx.fillText(`${row.neighborhood} • ${row.startTime}${row.endTime?` – ${row.endTime}`:""}`,92,y+50);ctx.fillStyle="#cbd4e5";ctx.font="600 24px Arial";ctx.fillText(row.hostName?`Hosted by ${escapeText(row.hostName)}`:"Host not listed",92,y+94);y+=rowHeight;}footer(ctx,w,h);}); }
function renderEnd(payload: LockedRoundupPayload, format: RoundupRenderFormat) { return canvasSlide(format,(ctx,w,h)=>{brand(ctx,w);ctx.textAlign="center";ctx.fillStyle="#fff";ctx.font=`900 ${format==="story"?76:64}px Arial`;const lines=wrap(ctx,"Find your next karaoke night",w-180);lines.forEach((line,i)=>ctx.fillText(line,w/2,h*.38+i*86));ctx.fillStyle="#49d9ff";ctx.font="900 56px Arial";ctx.fillText("SingHUB.app",w/2,h*.62);ctx.fillStyle="#d9e1ef";ctx.font="700 31px Arial";ctx.fillText("Search by night, neighborhood, venue or host.",w/2,h*.69);ctx.fillStyle="#ff4daf";ctx.font="800 28px Arial";ctx.fillText(`${payload.weekday} • ${payload.date}`,w/2,h*.76);footer(ctx,w,h);}); }
function renderAll(payload: LockedRoundupPayload, format: RoundupRenderFormat): RenderedSlide[] { const slides:RenderedSlide[]=[{name:`${payload.date}-${format}-intro.png`,dataUrl:renderIntro(payload,format)}];payload.groups.forEach((group,index)=>slides.push({name:`${payload.date}-${format}-venues-${index+1}.png`,dataUrl:renderGroup(payload,group.venueEventIds,format)}));slides.push({name:`${payload.date}-${format}-end.png`,dataUrl:renderEnd(payload,format)});return slides; }
function download(slide:RenderedSlide){const a=document.createElement("a");a.href=slide.dataUrl;a.download=slide.name;document.body.appendChild(a);a.click();a.remove();}

export function RoundupEditor({ initialDraft, state, lockedPayload, lockedHash }:{initialDraft:RoundupDraft;state:RoundupState;lockedPayload?:LockedRoundupPayload;lockedHash?:string}){
  const [draft,setDraft]=useState(initialDraft);const [slides,setSlides]=useState<RenderedSlide[]>([]);const [format,setFormat]=useState<RoundupRenderFormat>("story");const [status,setStatus]=useState("");
  const blockers=useMemo(()=>draft.validation.filter(issue=>issue.severity==="blocker"),[draft.validation]);const editable=state==="draft";
  function updateRow(index:number,patch:Partial<RoundupVenueRow>){setDraft(current=>({...current,rows:current.rows.map((row,i)=>i===index?{...row,...patch}:row)}));}
  function move(index:number,delta:number){const target=index+delta;if(target<0||target>=draft.rows.length)return;setDraft(current=>{const rows=[...current.rows];[rows[index],rows[target]]=[rows[target],rows[index]];return{...current,rows:rows.map((row,i)=>({...row,number:i+1}))}})}
  function generate(next:RoundupRenderFormat){if(!lockedPayload)return setStatus("Lock the lineup before generating graphics.");const generated=renderAll(lockedPayload,next);setFormat(next);setSlides(generated);setStatus(`${generated.length} ${next} images generated from locked payload ${lockedHash?.slice(0,12)||""}.`)}
  return <div className="space-y-6">
    <section className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-fuchsia-300">Review lineup</p><h2 className="mt-1 text-2xl font-black">{editable?"Edit before locking":"Locked publishing payload"}</h2></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs font-black uppercase">{state}</span></div>
      <div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="p-2">Order</th><th className="p-2">Venue</th><th className="p-2">Neighborhood</th><th className="p-2">Start</th><th className="p-2">End</th><th className="p-2">Host</th></tr></thead><tbody>{draft.rows.map((row,index)=><tr key={row.eventId} className="border-t border-white/10"><td className="p-2"><div className="flex items-center gap-1"><span className="w-6 font-black text-cyan-200">{index+1}</span>{editable&&<><button type="button" onClick={()=>move(index,-1)} className="rounded border border-white/15 px-2">↑</button><button type="button" onClick={()=>move(index,1)} className="rounded border border-white/15 px-2">↓</button></>}</div></td>{(["venueName","neighborhood","startTime","endTime","hostName"] as const).map(field=><td className="p-2" key={field}>{editable?<input value={row[field]||""} onChange={e=>updateRow(index,{[field]:e.target.value})} className="min-w-32 rounded-lg border border-white/15 bg-slate-950 px-2 py-2 text-white"/>:<span>{row[field]||"—"}</span>}</td>)}</tr>)}</tbody></table></div>
      <div className="mt-4 flex flex-wrap gap-3">{editable&&<form action={saveEditedRoundupDraftAction} onSubmit={()=>setStatus("Saving and revalidating…")}><input type="hidden" name="draft" value={JSON.stringify(draft)}/><button className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-black text-slate-950">Save + Revalidate</button></form>}{state==="draft"&&<form action={markRoundupReviewedAction}><input type="hidden" name="date" value={draft.date}/><button disabled={blockers.length>0} className="rounded-xl bg-fuchsia-300 px-4 py-2.5 text-sm font-black text-slate-950 disabled:opacity-40">Mark Reviewed</button></form>}{state==="reviewed"&&<form action={lockRoundupAction}><input type="hidden" name="date" value={draft.date}/><button className="rounded-xl bg-emerald-300 px-4 py-2.5 text-sm font-black text-slate-950">Lock Lineup</button></form>}</div>
      {blockers.length>0&&<div className="mt-4 space-y-2">{blockers.map((issue,i)=><p key={i} className="rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-100">{issue.message}</p>)}</div>}
    </section>
    <section className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Generate & export</p><h2 className="mt-1 text-2xl font-black">Story and feed PNGs</h2><p className="mt-2 text-sm text-slate-400">Graphics are rendered in code from the locked snapshot only. The renderer does not re-query venue or host data.</p><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>generate("story")} disabled={!lockedPayload} className="rounded-xl bg-cyan-300 px-4 py-2.5 font-black text-slate-950 disabled:opacity-40">Generate Story 1080×1920</button><button onClick={()=>generate("feed")} disabled={!lockedPayload} className="rounded-xl bg-fuchsia-300 px-4 py-2.5 font-black text-slate-950 disabled:opacity-40">Generate Feed 1080×1350</button>{slides.length>0&&<button onClick={()=>slides.forEach((slide,i)=>setTimeout(()=>download(slide),i*180))} className="rounded-xl bg-white px-4 py-2.5 font-black text-slate-950">Download all {format} PNGs</button>}</div>{status&&<p className="mt-3 text-sm text-slate-300">{status}</p>}
      {slides.length>0&&<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{slides.map(slide=><div key={slide.name} className="rounded-2xl border border-white/10 bg-black/20 p-3"><img src={slide.dataUrl} alt={slide.name} className="w-full rounded-lg"/><button onClick={()=>download(slide)} className="mt-2 w-full rounded-lg border border-white/15 px-3 py-2 text-sm font-bold">Download PNG</button></div>)}</div>}
    </section>
  </div>
}
