'use client';
import {useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import Link from 'next/link';
import {trackEvent} from '@/lib/analytics';
import './bandNotes.css';
type Role='singers'|'venues'|'hosts'|'hotels';
const notes:Record<Role,{title:string;text:string}[]>={
 singers:[{title:'Find your next room.',text:'Tonight shows scheduled karaoke for the current karaoke night. Search by neighborhood, host or the kind of room you want.'},{title:'Pick your kind of awesome.',text:'Check the venue’s photos, schedule and available details. Save spots worth coming back to. Some details are still being confirmed.'},{title:'Ready to sing? SingHERE.',text:'SingHERE opens that room’s signup link or tells you how to join the KJ’s list. The KJ runs the rotation.'},{title:'Keep the Gig Stub.',text:'At the venue, tap “I’m here.” Your first visit collects its Gig Stub. Return visits add to your history. Location is optional, and self-reported visits are labeled.'},{title:'Sing it. Keep it. Share it.',text:'Record the song you sang in My SingHUB to add a performance star. Share if you want. Gig Stubs record visits; stars record your self-reported performances.'}],
 venues:[{title:'You folks bring the room.',text:'A useful listing starts with accurate nights, times, hosts and the details that make your spot worth checking out.'},{title:'Show singers what you’ve got.',text:'Send real venue photos you can authorize us to use, plus a short description of your room. A complete profile is for every verified venue.'},{title:'Keep the lineup straight.',text:'Tell us about changed nights, cancelled shows and new KJs. Use Claim / Update to send corrections for review.'},{title:'Put the signup where singers find it.',text:'Have an existing karaoke signup link? Send it. Otherwise, SingHERE can direct singers to your KJ.'},{title:'Want more reach?',text:'Ask about SingHUB Partner for promotion, hotel exposure and marketing tools. We’ll confirm what’s available for your venue before you join.'}],
 hosts:[{title:'Your nights. Your name.',text:'Your profile brings your confirmed hosting nights, venue links and public details into one place.'},{title:'Give singers a feel for your show.',text:'Use Claim / Update profile to send your photo, bio, social links and the things singers should know before joining your rotation.'},{title:'Help us keep it current.',text:'Tell us about new gigs, schedule changes and substitutions. Older submissions don’t override newer confirmed schedules.'},{title:'Bring your existing tools.',text:'Send your signup, booking or tip link if you want it public. We don’t pretend a queue or song catalog is connected when it isn’t.'},{title:'Pass your card around.',text:'Use Share on your host profile to show people where to find you. Your public profile keeps your private contact details private.'}],
 hotels:[{title:'Your guests found their room.',text:'Now help them find a mic. A hotel guide organizes karaoke around the property, with nearby options, schedules and directions.'},{title:'One scan. Local nights.',text:'Place your hotel’s unique QR where guests will see it. The guide opens in their browser, with no app download needed.'},{title:'Let guests make a plan.',text:'Guests can choose tonight or this week, add venues to a trip plan and sign in by email to keep their picks.'},{title:'Choose the right edition.',text:'The free Guest Guide leads with SingHUB. Concierge Edition leads with the hotel’s reviewed branding, powered by SingHUB.'},{title:'Set it up. Test the whole trip.',text:'Review real property imagery and permission, print the collateral, then scan and try it on a phone. Contact SingHUB to arrange your property’s guide.'}],
};
export function BandNotes(){
 const path=usePathname();const dialog=useRef<HTMLDialogElement>(null);const [role,setRole]=useState<Role>('singers');const [step,setStep]=useState(0);
 useEffect(()=>{dialog.current?.close();},[path]);
 if(path.startsWith('/admin')||path.startsWith('/auth')||path.startsWith('/scout'))return null;
 const current=notes[role][step];
 const start=()=>{setRole(path.startsWith('/hotel')?'hotels':path.startsWith('/hosts')?'hosts':'singers');setStep(0);dialog.current?.showModal();trackEvent('quick_tour_open',{page_path:path});};
 return <aside className="band-notes-launcher"><button onClick={start} type="button">New around here? Read the band notes ↗</button><dialog ref={dialog} className="band-notes-dialog" aria-labelledby="band-notes-title" onClick={event=>{if(event.target===event.currentTarget)event.currentTarget.close();}}><button type="button" className="band-notes-close" aria-label="Close band notes" onClick={()=>dialog.current?.close()}>×</button><p className="band-notes-label">SingHUB · Notes from backstage</p><div className="band-notes-roles" aria-label="Choose your tour">{(['singers','venues','hosts','hotels'] as Role[]).map(r=><button key={r} aria-pressed={r===role} onClick={()=>{setRole(r);setStep(0);}}>{r==='hosts'?'KJs':r[0].toUpperCase()+r.slice(1)}</button>)}</div><p className="band-notes-count">Track {step+1} / {notes[role].length}</p><h2 id="band-notes-title">{current.title}</h2><p className="band-notes-copy">{current.text}</p><div className="band-notes-actions">{step>0&&<button type="button" onClick={()=>setStep(s=>s-1)}>Back</button>}{step<notes[role].length-1?<button type="button" onClick={()=>setStep(s=>s+1)}>Next track →</button>:<><Link href={role==='venues'?'/claim-listing':role==='hosts'?'/hosts':role==='hotels'?'mailto:hello@singhub.app':'/find-karaoke'} onClick={()=>dialog.current?.close()}>{role==='venues'?'Send your venue info':role==='hosts'?'Find your host profile':role==='hotels'?'Contact SingHUB':'Find your next room'}</Link><button type="button" onClick={()=>dialog.current?.close()}>Got it. Let’s go.</button></>}</div></dialog></aside>;
}
