import Link from 'next/link';
import {notFound} from 'next/navigation';
import {getHotelPackage} from '@/lib/hotelPackage.server';
import {PackageReview} from '@/components/hotel/package/PackageReview';
import './package.css';
export const dynamic='force-dynamic';
export const metadata={title:'Hotel deployment package | SingHUB Admin',robots:{index:false,follow:false}};
export default async function PackagePage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const model=await getHotelPackage(slug);if(!model)notFound();
 return <main className="hotel-package-admin"><Link href="/admin/hotels">← Hotel media</Link><p className="package-eyebrow">HOTEL DEPLOYMENT PACKAGE</p><h1>{model.hotel.shortName}</h1><p>{model.hotel.address}</p><p>One hotel record. Two editions. The preview below loads the actual print template.</p><div className="package-links"><Link href={`/hotelexperience/${model.hotel.slug}?edition=guest`} target="_blank">Open Guest Guide</Link><Link href={`/hotelexperience/${model.hotel.slug}?edition=concierge`} target="_blank">Open Concierge Edition</Link><a href={`/admin/hotels/${model.hotel.slug}/package/manifest`}>Download source manifest</a></div><PackageReview model={model}/>
 {(['guest','concierge'] as const).map(edition=><section key={edition}><h2>{edition==='guest'?'Free SingHUB Guest Guide':'Hotel Concierge Edition'}</h2><p>{model.readiness[edition]?'Asset review complete. Production print available.':'Internal preview. Production export waits for asset approval.'}</p><div className="package-output-grid">{(['elevator','desk-tent'] as const).map(format=>{
 const base=`/admin/hotels/${model.hotel.slug}/package/print?edition=${edition}&format=${format}`;const preview=base+'&mode='+(model.readiness[edition]?'production':'draft');
 return <article key={format} className="package-output"><h3>{format==='elevator'?'Elevator insert':'Portrait desk tent inserts'}</h3><p>{format==='desk-tent'?'4 × 6 inch portrait faces · two per landscape Letter sheet':'8.5 × 11 inches · portrait US Letter'}</p><div className="package-links"><a href={preview} target="_blank">{model.readiness[edition]?'Open production print':'Open internal print'}</a>{model.readiness[edition]&&<a href={base+'&mode=production'} target="_blank">Print production / PDF</a>}<a href={`/api/hotels/${model.hotel.slug}/qr?edition=${edition}&format=${format}`}>Download QR SVG</a></div><div className={"package-print-preview"+(format==='desk-tent'?' landscape':'')}><iframe title={`${edition} ${format} actual print preview`} src={preview+'&embed=1'} loading="lazy"/></div></article>;
 })}</div></section>)}<section className="package-checklist"><h2>Property test</h2><ol><li>Save reviewed imagery and branding.</li><li>Print at actual size, with backgrounds on and browser headers off.</li><li>Trim the two 4 × 6 inch portrait inserts along the cut guides. Place them back-to-back in a desk holder.</li><li>Scan the physical QR on a guest phone. Check tonight’s results, directions and saving a plan.</li><li>Place approved pieces at the desk and elevator. Confirm staff can explain the guide in one sentence.</li></ol></section></main>;
}
